#
# ------------------------------------------------------------
# Copyright (c) All rights reserved
# SiLab, Institute of Physics, University of Bonn
# ------------------------------------------------------------
#
# SVN revision information:
#  $Rev::                       $:
#  $Author::                    $:
#  $Date::                      $:
#

USB:
    bit_file       : "top.bit"  # adjust path if necessary
    board_id       : 
    avoid_download : False

cmd:
    OUTPUT_MODE : 0  # 0: positive edge (default), 2: Manchester encoding

tlu:
    TRIGGER_MODE        : 0
    EN_INVERT_TRIGGER   : 0
    EN_WRITE_TIMESTAMP  : 0
    TRIGGER_LOW_TIMEOUT : 0

rx_4:
    INVERT_RX : 0  # 0: IBL modules (default), 1: DBM modules

rx_3:
    INVERT_RX : 0
    
rx_2:
    INVERT_RX : 0

rx_1:
    INVERT_RX : 0
